### ISSUE TITLE
OutOfMemoryError: CUDA out of memory in `refine-tomogram`

### ISSUE THREAD

**Issue by rdrighetto** [MLI-lab/DeepDeWedge#21]
Hi Simon,

When trying to predict a tomogram (`ddw refine-tomogram`) on an RTX-4090 card (24 GB of GPU memory) I always stumble upon the following error:
```
│ /scicore/projects/scicore-p-structsoft/ubuntu/software/Miniconda3/miniconda3 │
│ _python3.12.1/envs/DeepDeWedge-ub/lib/python3.10/site-packages/ddw/utils/fou │
│ rier.py:18 in ifft_3d                                                        │
│                                                                              │
│   15 │   Inverse 3D Fourier transform with fftshift.                         │
│   16 │   """                                                                 │
│   17 │   fft_dim = (-1, -2, -3)                                              │
│ ❱ 18 │   return fft.ifftn(fft.ifftshift(tomo, dim=fft_dim), dim=fft_dim, nor │
│   19                                                                         │
│   20                                                                         │
│   21 def apply_fourier_mask_to_tomo(tomo, mask, output="real"):              │
╰──────────────────────────────────────────────────────────────────────────────╯
OutOfMemoryError: CUDA out of memory. Tried to allocate 4.00 GiB. GPU 0 has a 
total capacity of 23.55 GiB of which 1.03 GiB is free. Including non-PyTorch 
memory, this process has 22.50 GiB memory in use. Of the allocated memory 20.03 
GiB is allocated by PyTorch, and 2.01 GiB is reserved by PyTorch but 
unallocated. If reserved but unallocated memory is large try setting 
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See 
documentation for Memory Management  
(https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

I have these lines in my `.yaml` file:
```
refine_tomogram:
    model_checkpoint_file: "./logs/version_0/checkpoints/epoch/epoch=599.ckpt"
    subtomo_overlap: 32
    batch_size: 16
```
If I remove the `subtomo_overlap` and `batch_size` entries to use the default values, I get the same error.
Perhaps also relevant, I have done the model fitting with the following parameters:
```
  subtomo_size: 80
  subtomo_extraction_strides: [80, 80, 80]
```

However, if I run the prediction on A40 cards (48 GB of GPU memory), it runs fine. That is, `ddw refine-tomogram` is very memory hungry 😋 
Is there anything I can do to reduce the GPU memory footprint for prediction? On our cluster, I'd prefer using RTX-3090 and RTX-4090 cards (which are fine for training) because they are way more available than A40 cards.

Thanks a lot!

**Comment by SimWdm** [comment]
Hi Ricardo,

did you fit the model on the RTX cards or on the A40 cards, and which batch size did you use for fitting?

I am asking because model fitting requires more memory than tomogram refinement when the batch size is the same. So if fitting works on one type of GPU with batch size X, then refinement should also work on that GPU with the same batch size.

Another thing that comes to my mind is: Did you specify the `batch_size` in the `shared` field of the config? This could lead to the default batch size of 1 not being used for refinement. To rule this out, could you try refinement with explicitly specifying `batch_size: 1` in the `refine-_tomogram` field of the config file?

Best,
Simon

**Comment by rdrighetto** [comment]
Hi Simon,

> did you fit the model on the RTX cards or on the A40 cards, and which batch size did you use for fitting?
I have tried both. Fitting works without issues on both cards. 

> Another thing that comes to my mind is: Did you specify the batch_size in the shared field of the config? This could lead to the default batch size of 1 not being used for refinement. To rule this out, could you try refinement with explicitly specifying batch_size: 1 in the refine-_tomogram field of the config file?
I specify `batch_size` separately for fitting and refining. In the `fit_model` section of the .yaml file I use `batch_size: 5`. In the `refine_tomogram` section I have tried varying `batch_size` with values of 1, 5, 8, 16 and in all cases I run into this error when running on RTX cards, but not A40. Very strange.

I suspect I should use a smaller `subtomo_size` (currently at 80). But then, this value is still fine for fitting on the RTX cards 🤔

**Comment by SimWdm** [comment]
Ok then the error is probably not caused by the network inference. That's good to know.

I noticed that the error occurs during the Fourier transformation. In `refine-tomogram`, I apply a missing wedge filter to the input tomogram. For that, the Fourier transform of the input tomogram is computed. If the tomogram is large, this could possibly require a lot of memory. How large is your tomogram?

**Comment by rdrighetto** [comment]
this would make sense, my tomogram is 1024 x 1024 x 512

**Comment by SimWdm** [comment]
I think that's it! I have just tried applying the wedge filter to a tomogram of shape `512 x 1024 x 1024` and, checking with nvidia-smi, it seems that this operation alone requires around 24895MiB memory. 

If your tomogram contains large "empty" regions you could consider cropping it. 
I could also try to get rid of the filtering of the whole tomogram and maybe filter the sub-tomograms instead. 🤔

**Comment by rdrighetto** [comment]
Thanks for checking!
Since the fitting step is done entirely on sub-tomograms, I think applying the filtering to sub-tomograms also in refinement would make sense (assuming quality of the output is not downgraded).
Alternatively, could this filtering step be carried out on the CPU (maybe too slow)?
Out of curiosity, what tomogram sizes do you usually work with?

**Comment by SimWdm** [comment]
> Out of curiosity, what tomogram sizes do you usually work with?
I think I have processed a `512 x 1024 x1024` tomogram before but we have rather large GPUs as our group does mainly machine learning so I never ran into the memory issue.
I don't have a standard size for tomograms. Most of the time, I resize them to get a voxel size of 1nm and then work with whatever that results in. But they are usually quite a bit smaller than `512 x 1024 x 1024`. 

> Alternatively, could this filtering step be carried out on the CPU (maybe too slow)?

I have just created a new branch in which the wedge is applied on the CPU. It's definitely slower but not much. Interestingly, applying the wedge on CPU seems to use less memory than doing it on GPU. 🤔 

You can try the new version by running
```
git fetch origin
git checkout 21-outofmemoryerror-cuda-out-of-memory-in-refine-tomogram
```
and re-installing `ddw`.
Could you check how much CPU memory the `refine-tomogram` roughly uses? I'm just curious how it compares to what I got. 

If the fix works for you, I'll merge it into main.

**Comment by rdrighetto** [comment]
Hi Simon, thanks for providing this solution so quickly!

At first, just switching to the new branch was not enough. Interestingly though, now the OOM error would happen AFTER the refinement of both tomo0 and tomo1 were completed (?) instead of before. It was definitely using less memory on the GPU, but there was still not enough left.
I managed to make the job complete on the RTX-4090 using the new branch, but also setting `batch_size` to 1 (instead of 5) and `num_workers` to 8 instead of 10 (not sure if that really mattered) and while these were freeing more memory, what finally did the trick was setting the following environment variable:
`export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True`
(I had tried this before with no success)
The `ddw refine-tomogram` process seems to have used ~36 GB of CPU memory as observed using `top` . Speed-wise I did not notice any significant difference (other than having to reduce the batch size).

So the good news is that the new branch does seem to fix the issue, but I still had to change a few extra things to finally make it work on the RTX-4090. I am in favor of merging.

**Comment by SimWdm** [comment]
Glad to hear that it worked! Seems like these GPU things can get really tricky and that some fixes are hardware-dependent :/

> Interestingly though, now the OOM error would happen AFTER the refinement of both tomo0 and tomo1 were completed (?) instead of before.

This sounds like reassembling and adding tomo0 and tomo1 could be the reason for OOM. I have just pushed another update to the branch. Now, the reassembling should be done on the CPU as well.

**Comment by rdrighetto** [comment]
Hi Simon!

I just tested this latest update in the `21-outofmemoryerror-cuda-out-of-memory-in-refine-tomogram` branch and now it worked to refine the tomo on the RTX-4090 using `batch_size: 5` and _without_ using `export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True`. Looks like we have a good fix for this issue. Thanks a lot for providing it so quickly!

**Comment by SimWdm** [comment]
Great news! I will merge the branch into main.

**Comment by frozenmess** [comment]
I had this issue with refine-tomogram in December, the update fixed it. Now I am getting this error with fit-model and have not found a solution. Here is the error: 

[rank0]: OutOfMemoryError: CUDA out of memory. Tried to allocate 864.00 MiB. GPU 0 has a total capacity of 19.70 GiB of which 446.12 MiB is free. Including non-PyTorch 
[rank0]: memory, this process has 19.23 GiB memory in use. Of the allocated memory 18.38 GiB is allocated by PyTorch, and 446.77 MiB is reserved by PyTorch but 
[rank0]: unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation
[rank0]: for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Epoch 0:   0%|          | 0/76 [01:03<?, ?it/s]                                                                                                                 
[rank0]:[W228 13:12:52.577298771 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())

**Comment by SimWdm** [comment]
Hi @frozenmess ,

your GPU is running out of memory during model fitting, which requires much more GPU memory than refinement due to the computation of gradients. 

To fix this you can try a smaller model (set chans to, e.g., `chans: 32`) in your config. You can also reduce the `batch_size`, and the `subtomo_size`, but I recommend trying a smaller model first.

I hope this helps. Please don't hesitate to reach out again if you have any further questions.
