### ISSUE TITLE
NCCL timeout error during training

### ISSUE THREAD

**Issue by Phaips** [MLI-lab/DeepDeWedge#22]
Hi Simon,

Thanks for your effort of promptly fixing errors! Currently running DDW on the` 21-outofmemoryerror-cuda-out-of-memory-in-refine-tomogram` branch I stumbled across this error:

```
[rank1]:[E ProcessGroupNCCL.cpp:523] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=44, OpType=ALLREDUCE, NumelIn=6832129, NumelOut=6832129, Timeout(ms)=1800000) ran for 1800772 milliseconds before timing out.
[rank1]:[E ProcessGroupNCCL.cpp:537] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank1]:[E ProcessGroupNCCL.cpp:543] To avoid data inconsistency, we are taking the entire process down.
```

**Comment by Phaips** [comment]
the error seems to be gone re-running on a different GPU card..

**Comment by SimWdm** [comment]
Hi Philippe,

did you manage to resolve the issue on the original GPU as well?
The error looks related to multi GPU processing. Such things are always a bit tricky and hardware-specific tricks may be required in some cases :/

**Comment by Phaips** [comment]
Yeah it's a bit tricky indeed. I was running it on an A100 card with 4 GPU's where I ran into this error. Ricardo updated our ddw_pipeline script with inputs that worked for him (2 GPU's on a RTX4090 card) and it's seems to run fine :)
